### ISSUE TITLE
fix auth_endpoint

### ISSUE THREAD

**Issue by darshanime** [ChillarAnand/httpie-token-auth#1]
the current `auth_endpoint` is `'/api/token/new.json'`. It should be `'api/token/new.json'`
else it results in an incorrect endpoint being hit
```
WARNING Not Found: //api/token/new.json
WARNING "POST //api/token/new.json HTTP/1.1" 404 3102
```
The env var is nice, but the default should be fixed IMO

**Comment by ChillarAnand** [comment]
@darshanime Thank you for reporting the issue. It is fixed now. Thanks.

**Comment by ChillarAnand** [comment]
Published to PyPi. Please upgrade the package with `pip install -U httpie-token-auth`.
